# services:
#   mongodb:
#     image: "mongo"
#     volumes:
#       - data:/data/db
#     networks:
#       - mern-network
#     volumes:
#       - logs:/app/logs
#       - ./backend:/app
#       - /app/node_modules
#     depends_on:
#       - mongodb
#     networks:
#       - mern-network
#   frontend:
#     build: ./frontend
#     restart: unless-stopped
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend/src:/app/src
#     stdin_open: true
#     tty: true
#     depends_on:
#       - backend
#     networks:
#       - mern-network

# networks:
#    mern-network:
#      driver: bridge

# volumes:
#   data:
#   logs:


version: '3.8'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    # .env gave error
    ports:
      - "4000:4000"
    # where backend is stored
    volumes:
      - ./backend:/app
      - /app/node_modules
    

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend/src:/app/src
      - /app/src/node_modules


